# Generated by Django 4.1.1 on 2024-03-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visualize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField(max_length=5)),
                ('intensity', models.IntegerField(max_length=5)),
                ('sector', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=20)),
                ('insight', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=5000)),
                ('region', models.CharField(max_length=100)),
                ('start_year', models.IntegerField(max_length=5)),
                ('impact', models.CharField(max_length=50)),
                ('added', models.CharField(max_length=100)),
                ('published', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('relevance', models.IntegerField(max_length=5)),
                ('pestle', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=10000)),
                ('likelihood', models.IntegerField(max_length=5)),
            ],
        ),
    ]
