# Generated by Django 4.1.1 on 2024-03-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualize',
            name='added',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='end_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='impact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='insight',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='intensity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='likelihood',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='pestle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='published',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='relevance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='sector',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='start_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='title',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='topic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='visualize',
            name='url',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
